name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: false

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run NUKE
      run: bash ./build.sh
      env:
        NuGetApiKey: ${{ secrets.NUGETAPIKEY }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./Artifacts/*
